//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject_Sayed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Stuff
    {
        public int StuffID { get; set; }       
        public string StuffName { get; set; }       
        public Nullable<int> Age { get; set; }        
        public string State { get; set; }        
        public string Country { get; set; }
    }
}
